### ISSUE TITLE
Convert single color to transparent

### ISSUE THREAD

**Issue by kitolog** [gre/gl-react-color-matrix#2]
Hi!
As I understand, I can convert color on image to transparent using color-matrix.
Can you help me to convert one color on image (#f8f8f8) to transparent on png image?

**Comment by gre** [comment]
No I don't think you can use gl-react-color-matrix for this usecase.
You will need to write your own effect.

here is an hint on how to implement a shader that would allow to turn a color transparent (not tested):

``` glsl
varying vec2 uv;
uniform vec3 color; // the color you want to make transparent. e.g red is [ 1.0, 0.0, 0.0 ]
uniform float threshold; // make it small, like 0.01
uniform sampler2D t; // the texture to apply the effect on

void main () {
  vec4 c = texture2D(t, uv);
  c.a *= smoothstep(0.0, threshold, distance(color, c.rgb));
  gl_FragColor = c;
}
```

**Comment by gre** [comment]
sounds like you can make a new effect module out of this if you want :)
