### ISSUE TITLE
Error on latest React Native versions [RN 0.50.3]

### ISSUE THREAD

**Issue by themakerman** [gre/gl-react-color-matrix#3]
```
  "dependencies": {
                "gl-react": "v3",
                "gl-react-color-matrix": "^1.1.0",
                "gl-react-dom": "^2.2.9",
                "gl-react-native": "^2.47.0",
                "prop-types": "^15.6.0",
                "react": "16.0.0",
                "react-native": "^0.50.3",
                "react-native-webgl": "^0.7.0"
        },"
```
Here are my dependencies. I am aware Proptypes was moved to different package but editing line 3 import in colorMatrix.js to import PropTypes from 'prop-types' even did not fixed it. I hope i was trying to fix the right thing. Anyways here's the screenshot of error.

![simulator screen shot - iphone 6 - 2017-11-15 at 14 34 31](https://user-images.githubusercontent.com/14818804/32828625-a9aaf6d2-ca15-11e7-8aec-d8fda5496578.png)

**Comment by benjaminkoetting** [comment]
I got the same error today trying to get the "old" version running, because I need to get the result als image.

The error is the old usage of PropTypes:

```
const {
  PropTypes
} = React;
```

have to change to these in new react-native versions:

`import PropTypes from 'prop-types';`

Br,
Ben

**Comment by themakerman** [comment]
yup. It solves the issue.
